export class Key {
  static readonly BACKSPACE = 0     // \b - backspace
  static readonly TAB = 1           // \b -tab
  static readonly CLEAR = 2         // clear
  static readonly RETURN = 3        // \r - return
  static readonly PAUSE = 4         // pause
  static readonly ESCAPE = 5        // ^[ - escape
  static readonly SPACE = 6         // space
  static readonly EXCLAIM = 7       // ! - exclaim
  static readonly QUOTEDBL = 8      // " - quotedbl
  static readonly HASH = 9          // # - hash
  static readonly DOLLAR = 10       // # - dollar
  static readonly AMPERSAND = 11    // # - ampersand
  static readonly LEFTPAREN = 12    // ( - left parenthesis
  static readonly RIGHTPAREN = 13   // ) - right parenthesis
  static readonly ASTERISK = 14     // * asterisk
  static readonly PLUS = 15         // + - plus sign
  static readonly COMMA = 16        // , - comma
  static readonly MINUS = 17        // - - minus sign
  static readonly PERIOD = 18       // . - period
  static readonly SLASH = 19        // / - forward slash
  static readonly K_0 = 20          // 0
  static readonly K_1 = 21          // 1
  static readonly K_2 = 22          // 2
  static readonly K_3 = 23          // 3
  static readonly K_4 = 24          // 4
  static readonly K_5 = 25          // 5
  static readonly K_6 = 26          // 6
  static readonly K_7 = 27          // 7
  static readonly K_8 = 28          // 8
  static readonly K_9 = 29          // 9
  static readonly COLON = 30        // : - colon
  static readonly SEMICOLON = 31    // ; - semicolon
  static readonly LESS = 32         // < - less-than sign
  static readonly EQUALS = 33       // = - equals sign
  static readonly GREATER = 34      // > - greater-than sign
  static readonly QUESTION  = 35    // ? - question mark
  static readonly AT = 36           // @ - at
  static readonly LEFTBRACKET = 37  // [ - left bracket
  static readonly BACKSLASH = 38    // \ - backslash
  static readonly RIGHTBRACKET = 39 // ] -right bracket
  static readonly CARET = 40        // ^ - caret
  static readonly UNDERSCORE = 41   // _ - underscore
  static readonly BACKQUOTE = 42    // ` - grave
  static readonly K_A = 43          // a
  static readonly K_B = 44          // b
  static readonly K_C = 45          // c
  static readonly K_D = 46          // d
  static readonly K_E = 47          // e
  static readonly K_F = 48          // f
  static readonly K_G = 49          // g
  static readonly K_H = 50          // h
  static readonly K_I = 51          // i
  static readonly K_J = 52          // j
  static readonly K_K = 53          // k
  static readonly K_L = 54          // l
  static readonly K_M = 55          // m
  static readonly K_N = 56          // n
  static readonly K_O = 57          // o
  static readonly K_P = 58          // p
  static readonly K_Q = 59          // q
  static readonly K_R = 60          // r
  static readonly K_S = 61          // s
  static readonly K_T = 62          // t
  static readonly K_U = 63          // u
  static readonly K_V = 64          // v
  static readonly K_W = 65          // w
  static readonly K_Y = 66          // y
  static readonly K_Z = 67          // z
  static readonly DELETE = 68       // delete
  static readonly KP_0 = 69         // keypad 0
  static readonly KP_1 = 70         // keypad 1
  static readonly KP_2 = 71         // keypad 2
  static readonly KP_3 = 72         // keypad 3
  static readonly KP_4 = 73         // keypad 4
  static readonly KP_5 = 74         // keypad 5
  static readonly KP_6 = 75         // keypad 6
  static readonly KP_7 = 76         // keypad 7
  static readonly KP_8 = 77         // keypad 8
  static readonly KP_9 = 79         // keypad 9
  static readonly KP_PERIOD = 80    // keypad .
  static readonly KP_DIVIDE = 81    // keypad /
  static readonly KP_MULTIPLY = 82  // keypad *
  static readonly KP_MINUS = 83     // keypad -
  static readonly KP_PLUS = 84      // keypad +
  static readonly KP_ENTER = 85     // keypad enter
  static readonly KP_EQUALS = 86    // keypad =
  static readonly UP = 87           // up arrow
  static readonly DOWN = 88         // down arrow
  static readonly RIGHT = 89        // right arrow
  static readonly LEFT = 90         // left arrow
  static readonly INSERT = 91       // insert
  static readonly HOME = 92         // home
  static readonly END = 93          // end
  static readonly PAGEUP = 94       // page up
  static readonly PAGEDOWN = 95     // page down
  static readonly F1 = 96           // F1
  static readonly F2 = 97           // F2
  static readonly F3 = 98           // F3
  static readonly F4 = 99           // F4
  static readonly F5 = 100          // F5
  static readonly F6 = 101          // F6
  static readonly F7 = 102          // F7
  static readonly F8 = 103          // F8
  static readonly F9 = 104          // F9
  static readonly F10 = 105         // F10
  static readonly F11 = 106         // F11
  static readonly F12 = 107         // F12
  static readonly F13 = 108         // F13
  static readonly F14 = 109         // F14
  static readonly F15 = 110         // F15
  static readonly NUMLOCK = 111     // numlock
  static readonly CAPSLOCK = 112    // capslock
  static readonly SCROLLOCK = 113   // scrollock
  static readonly RSHIFT = 114      // right shift
  static readonly LSHIFT = 115      // left shift
  static readonly RCTRL = 116       // right control
  static readonly LCTRL = 117       // left control
  static readonly RALT = 118        // right alt
  static readonly LALT = 119        // left alt
  static readonly RMETA = 120       // right meta
  static readonly LMETA = 121       // left meta
  static readonly LSUPER = 122      // left Windows key
  static readonly RSUPER = 123      // right Windows key
  static readonly SHIFT = 124       // any shift
  static readonly CTRL = 125        // any control
  static readonly ALT = 126         // any alt
  static readonly META = 127        // any meta
  static readonly SUPER = 128       // any Windows key
}
