export type BlendFunc = 
  | 'ZERO'
  | 'ONE'
  | 'SRC_COLOR'
  | 'ONE_MINUS_SRC_COLOR'
  | 'DST_COLOR'
  | 'ONE_MINUS_DST_COLOR'
  | 'SRC_ALPHA'
  | 'ONE_MINUS_SRC_ALPHA'
  | 'DST_ALPHA'
  | 'ONE_MINUS_DST_ALPHA'
  | 'CONSTANT_COLOR'
  | 'ONE_MINUS_CONSTANT_COLOR'
  | 'CONSTANT_ALPHA'
  | 'ONE_MINUS_CONSTANT_ALPHA'
  | 'SRC_ALPHA_SATURATE'

export const __blendFuncDic: Record<string, number> = {
  ZERO: 0,
  ONE: 1,
  SRC_COLOR: 768,
  ONE_MINUS_SRC_COLOR: 769,
  DST_COLOR: 774,
  ONE_MINUS_DST_COLOR: 775,
  SRC_ALPHA: 770,
  ONE_MINUS_SRC_ALPHA: 771,
  DST_ALPHA: 772,
  ONE_MINUS_DST_ALPHA: 773,
  CONSTANT_COLOR: 32769,
  ONE_MINUS_CONSTANT_COLOR: 32770,
  CONSTANT_ALPHA: 32771,
  ONE_MINUS_CONSTANT_ALPHA: 32772,
  SRC_ALPHA_SATURATE: 776
}